grief:
  female: [1, 4, 7, 15, 16, 17, 21]  
  male: [1, 4, 15]                   

joy:
  female: [6, 7, 12, 25]  
  male: [6, 7, 12, 25]    

disgust:
  female: [4, 7, 9, 16, 19, 25, 26]  
  male: [4, 7, 9, 16, 19, 25, 26]    

outofbreath:
  female: [25, 26, 27]  
  male: [25, 26, 27]    

pain:
  female: [4, 6, 7, 9, 15, 16, 17, 25]  
  male: [4, 6, 7, 9, 15, 16, 17, 25]    

anger:
  female: [4, 7, 17, 24] 
  male: [4, 7, 17, 23]    

amazement:
  female: [1, 2, 5, 25, 27, 38] 
  male: [1, 2, 5, 25, 26, 38]    

cheekiness:
  female: [6, 7, 12, 14, 25] 
  male: [6, 7, 12, 14, 25]    

sadness:
  female: [1, 4, 7, 15, 16, 17, 21]  
  male: [1, 4, 15]                   

fear:
  female: [1, 2, 4, 5, 15, 16, 21, 25, 27, 58]  
  male: [1, 2, 4, 5, 25, 26, 58]                 


